export const Logoslist = [
  { path: "/logos/1.png", alt: "" },
  { path: "/logos/2.png", alt: "" },
  { path: "/logos/3.png", alt: "" },
  { path: "/logos/4.png", alt: "" },
  { path: "/logos/5.png", alt: "" },
  { path: "/logos/6.png", alt: "" },
  { path: "/logos/7.png", alt: "" },
  { path: "/logos/8.png", alt: "" },
  { path: "/logos/9.png", alt: "" },
  { path: "/logos/10.png", alt: "" },
  { path: "/logos/11.png", alt: "" },
  { path: "/logos/12.png", alt: "" },
  { path: "/logos/13.png", alt: "" },
  { path: "/logos/14.png", alt: "" },
  { path: "/logos/15.png", alt: "" },
  { path: "/logos/16.png", alt: "" },
  { path: "/logos/17.png", alt: "" },
  { path: "/logos/18.png", alt: "" },
  { path: "/logos/19.png", alt: "" },
  { path: "/logos/20.png", alt: "" },
  { path: "/logos/21.png", alt: "" },
  { path: "/logos/22.png", alt: "" },
  { path: "/logos/23.png", alt: "" },
] as const;
